# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'My Reviews' do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
end
